# Generated by Django 4.2.5 on 2023-09-25 08:28

import dashboard.product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_product', '0002_remove_product_location_product_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to=dashboard.product.models.img_directory_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='img1',
            field=models.ImageField(upload_to=dashboard.product.models.img_directory_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='img2',
            field=models.ImageField(upload_to=dashboard.product.models.img_directory_path),
        ),
    ]
